services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.home.neumanf.com`)
      - traefik.http.routers.n8n.entrypoints=https
      - traefik.http.routers.n8n.tls=true
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - glance.name=N8N
      - glance.icon=sh:n8n
      - glance.url=https://n8n.home.neumanf.com
      - glance.id=n8n
      - glance.category=automation
    networks:
      - traefik
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=http://n8n.home.neumanf.com
      - GENERIC_TIMEZONE=America/Recife
      - TZ=America/Recife
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data:

networks:
  traefik:
    external: true
