services:
  omni-tools:
    container_name: omni-tools
    image: iib0011/omni-tools:latest
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.omnitools.rule=Host(`omnitools.home.neumanf.com`)
      - traefik.http.routers.omnitools.entrypoints=https
      - traefik.http.routers.omnitools.tls=true
      - traefik.http.services.omnitools.loadbalancer.server.port=80
networks:
  traefik:
    external: true
