services:
  adguard:
    image: "adguard/adguardhome:latest"
    container_name: adguard
    restart: unless-stopped
    network_mode: host
    volumes:
      - adguard:/opt/adguardhome
    labels:
      glance.name: Adguard
      glance.icon: sh:adguard-home
      glance.url: http://minipc.intelbras.local:3000
      glance.category: network
volumes:
  adguard:
