services:
  calibre:
    image: linuxserver/calibre-web:latest
    container_name: calibre
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - ./data:/config
      - ./books:/books
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre.rule=Host(`calibre.home.neumanf.com`)
      - traefik.http.routers.calibre.entrypoints=web
      - traefik.http.services.calibre.loadbalancer.server.port=8083
networks:
  traefik:
    external: true
